# Generated by Django 4.2.1 on 2023-06-17 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('clinicID', models.AutoField(primary_key=True, serialize=False)),
                ('clinicName', models.CharField(max_length=100)),
                ('clinicAddress', models.CharField(max_length=100)),
                ('clinicNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicOwner',
            fields=[
                ('ownerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('homeAddress', models.CharField(max_length=250)),
                ('contactNum', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patientsID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('homeAddress', models.CharField(max_length=250)),
                ('contactNum', models.CharField(max_length=50)),
                ('emergencyName', models.CharField(max_length=100)),
                ('emergencyMiddleName', models.CharField(max_length=100)),
                ('emergencyLastName', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('emergencyContactNum', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('textID', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1000)),
                ('clinicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('patientsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinicowner')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=1000)),
                ('is_Approved', models.BooleanField(default=False)),
                ('clinicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('patientsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('passw', models.CharField(max_length=250)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinicowner')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients')),
            ],
        ),
    ]
