# Generated by Django 4.2.1 on 2023-06-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduledDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='ownerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinicowner'),
        ),
        migrations.AddField(
            model_name='clinicavailability',
            name='availability',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicowner',
            name='bday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='availability',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='bday',
            field=models.DateField(null=True),
        ),
    ]
