# Generated by Django 4.2.1 on 2023-06-20 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_bookeddate_booking_scheduleddate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('bday', models.DateField(null=True)),
                ('sex', models.CharField(max_length=100)),
                ('homeAddress', models.CharField(max_length=250)),
                ('contactNum', models.CharField(max_length=50)),
                ('emergencyName', models.CharField(max_length=100)),
                ('emergencyMiddleName', models.CharField(max_length=100)),
                ('emergencyLastName', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('emergencyContactNum', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinicavailability',
            name='clinicID',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='patientsID',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='ownerID',
        ),
        migrations.RemoveField(
            model_name='doctoravailability',
            name='doctorID',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='patientsID',
        ),
        migrations.AddField(
            model_name='clinic',
            name='availability',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='clinicID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='ClinicAvailability',
        ),
        migrations.DeleteModel(
            name='ClinicOwner',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
        migrations.AddField(
            model_name='booking',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
