# Generated by Django 4.2.1 on 2023-06-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_remove_clinicavailability_clinicid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserClient',
        ),
    ]
