# Generated by Django 4.2.2 on 2023-06-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userclient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clinicEMailAdd',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
