# Generated by Django 4.2.2 on 2023-06-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_clinic_clinicemailadd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='availability',
        ),
    ]
