# Generated by Django 4.2.1 on 2023-07-11 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_clinic_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='availability',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='availDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='availTime',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('clinic_LocID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
            ],
        ),
    ]
