# Generated by Django 4.2.1 on 2023-07-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_doctoravailability_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
    ]
