# Generated by Django 4.2.1 on 2023-07-11 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userclient_is_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinicAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availDate', models.DateField(null=True)),
                ('availTime', models.TimeField(null=True)),
                ('clin_AvailID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
            ],
        ),
    ]
