# Generated by Django 4.2.3 on 2023-07-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_clinicavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclient',
            name='middleName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
