# Generated by Django 4.2.3 on 2023-07-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userclient_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclient',
            name='emergencyMiddleName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
