# Generated by Django 4.2.1 on 2023-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_userclient_emergencymiddlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='scheduledDate',
        ),
        migrations.AddField(
            model_name='clinic',
            name='availDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='availTime',
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(
            name='clinicAvailability',
        ),
    ]
