# Generated by Django 4.2.1 on 2023-07-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_booking_scheduleddate_clinic_availdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('apptStart', models.DateTimeField()),
                ('apptEnd', models.DateTimeField()),
                ('is_allDay', models.BooleanField(default=False)),
                ('bookingID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
            ],
        ),
    ]
