# Generated by Django 4.2.1 on 2023-07-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_calendar_apptend_alter_calendar_apptstart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
