# Generated by Django 4.2.1 on 2023-07-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_calendar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='location',
        ),
    ]
