# Generated by Django 4.2.3 on 2023-07-24 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0017_clinic_latitude_clinic_longitude_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ophthalmologist',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100)),
                ('bday', models.DateField(null=True)),
                ('sex', models.CharField(max_length=100)),
                ('homeAddress', models.CharField(max_length=250)),
                ('contactNum', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='doctoravailability',
            name='clinicID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ophthalmologist'),
        ),
    ]
