# Generated by Django 4.2.3 on 2023-07-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_ophthalmologist_alter_doctoravailability_clinicid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ophthalmologist',
            old_name='userID',
            new_name='opthID',
        ),
        migrations.AddField(
            model_name='clinic',
            name='opthID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ophthalmologist'),
        ),
    ]
