# Generated by Django 4.2.3 on 2023-07-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_userid_ophthalmologist_opthid_clinic_opthid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclient',
            name='is_status',
        ),
        migrations.AddField(
            model_name='ophthalmologist',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
    ]
