# Generated by Django 4.2.1 on 2023-07-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_userclient_is_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='userID',
        ),
    ]
