# Generated by Django 4.2.1 on 2023-07-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_clinic_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('service_List', models.CharField(max_length=1000)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
            ],
        ),
    ]
