# Generated by Django 4.2.1 on 2023-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_List',
        ),
        migrations.AddField(
            model_name='services',
            name='service_Information',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_Name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
