# Generated by Django 4.2.2 on 2023-07-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_services_service_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='apptTime',
            field=models.DateTimeField(null=True),
        ),
    ]
