# Generated by Django 4.2.2 on 2023-07-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_booking_appttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookedDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
