# Generated by Django 4.2.2 on 2023-07-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_booking_bookeddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookedDate',
        ),
    ]
