# Generated by Django 4.2.1 on 2023-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_booking_bookeddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='apptTime',
            new_name='appt_End_Time',
        ),
        migrations.AddField(
            model_name='booking',
            name='appoint_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='appt_Start_Time',
            field=models.DateTimeField(null=True),
        ),
    ]
