# Generated by Django 4.2.1 on 2023-12-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_appttime_booking_appt_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appt_End_Time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='appt_Start_Time',
            field=models.TimeField(null=True),
        ),
    ]
