# Generated by Django 4.2.1 on 2023-12-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_booking_appt_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appoint_Date',
            field=models.DateField(null=True),
        ),
    ]
