# Generated by Django 4.2.1 on 2023-12-05 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_booking_appoint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userclient'),
        ),
    ]
