# Generated by Django 4.2.1 on 2023-12-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_booking_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='serviceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.services'),
        ),
    ]
