# Generated by Django 4.2.1 on 2023-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_booking_serviceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_Approved',
            new_name='is_Accepted',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_Denied',
            field=models.BooleanField(default=False),
        ),
    ]
