# Generated by Django 4.2.1 on 2023-12-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_is_approved_booking_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('patientID', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=1000)),
                ('relationshipStatus', models.CharField(max_length=1000)),
                ('occupation', models.CharField(max_length=1000)),
                ('age', models.CharField(max_length=150)),
                ('medicalHistory', models.CharField(max_length=1000)),
                ('allergies', models.CharField(max_length=1000)),
                ('drugIntake', models.CharField(max_length=1000)),
                ('disorder', models.CharField(max_length=1000)),
                ('opthalNotes', models.CharField(max_length=1000)),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userclient')),
            ],
        ),
    ]
