# Generated by Django 4.2.1 on 2023-12-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_booking_is_status_patientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='opthalNotes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lastConsulation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='patientBooked',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='allergies',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='disorder',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='drugIntake',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medicalHistory',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='occupation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='opthalNotes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
