# Generated by Django 4.2.1 on 2023-12-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_booking_opthalnotes_patientprofile_lastconsulation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='patientBooked',
            new_name='appointmentRecord',
        ),
    ]
