# Generated by Django 4.2.1 on 2023-12-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_rename_patientbooked_patientprofile_appointmentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
