# Generated by Django 4.2.1 on 2023-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_booking_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
