# Generated by Django 4.2.1 on 2023-12-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_booking_is_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='prev_appoint_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='prev_appt_End_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='prev_appt_Start_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
