# Generated by Django 4.2.1 on 2023-12-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_booking_prev_appoint_date_booking_prev_appt_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelationReason',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
