# Generated by Django 5.0 on 2023-12-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_booking_cancelationreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('recordID', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=1000)),
                ('relationshipStatus', models.CharField(max_length=1000)),
                ('occupation', models.CharField(max_length=1000, null=True)),
                ('age', models.CharField(max_length=150, null=True)),
                ('medicalHistory', models.CharField(max_length=1000, null=True)),
                ('allergies', models.CharField(max_length=1000, null=True)),
                ('lastConsulation', models.CharField(max_length=1000, null=True)),
                ('drugIntake', models.CharField(max_length=1000, null=True)),
                ('disorder', models.CharField(max_length=1000, null=True)),
                ('opthalNotes', models.CharField(max_length=1000, null=True)),
                ('appointmentRecord', models.CharField(max_length=1000, null=True)),
                ('medicalCondition', models.CharField(max_length=1000, null=True)),
                ('familyHistoryOfEyeDisease', models.CharField(max_length=1000, null=True)),
                ('bookingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userclient')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
