# Generated by Django 5.0 on 2023-12-29 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_patientrecord_delete_patientprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPatient',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100)),
                ('bday', models.DateField(null=True)),
                ('sex', models.CharField(max_length=100)),
                ('homeAddress', models.CharField(max_length=250)),
                ('contactNum', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientContacts',
            fields=[
                ('pConID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('homeAddress', models.CharField(max_length=250)),
                ('contactNum', models.CharField(max_length=50)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
        migrations.DeleteModel(
            name='UserClient',
        ),
    ]
