# Generated by Django 5.0 on 2023-12-29 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_userpatient_patientcontacts_alter_booking_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='opthalNotes',
            new_name='declinedNotes',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='clinicID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='recordDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
