# Generated by Django 5.0 on 2023-12-29 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_rename_opthalnotes_booking_declinednotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='opthID',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='bookingID',
        ),
        migrations.AddField(
            model_name='ophthalmologist',
            name='clinicID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic'),
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('stafferID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100)),
                ('bday', models.DateField(null=True)),
                ('sex', models.CharField(max_length=100)),
                ('homeAddress', models.CharField(max_length=250)),
                ('contactNum', models.CharField(max_length=50)),
                ('is_Accepted', models.BooleanField(default=False)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
            ],
        ),
    ]
