# Generated by Django 5.0 on 2023-12-29 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_clinicstaff_user_usercontacts_delete_patientcontacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ophthalmologist',
            name='clinicID',
        ),
        migrations.AddField(
            model_name='clinic',
            name='opthID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ophthalmologist'),
        ),
    ]
