# Generated by Django 5.0 on 2024-01-07 07:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_ophthalmologist_clinicid_clinic_opthid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='age',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('textID', models.AutoField(primary_key=True, serialize=False)),
                ('messageContent', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('clinicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientClinicalObservation',
            fields=[
                ('pcObservationID', models.AutoField(primary_key=True, serialize=False)),
                ('refractionTest', models.CharField(max_length=1000, null=True)),
                ('diagnosticCodes', models.CharField(max_length=1000, null=True)),
                ('patientPrecribtion', models.CharField(max_length=1000, null=True)),
                ('snellenChart', models.CharField(max_length=1000, null=True)),
                ('contrastSensitivityTests', models.CharField(max_length=1000, null=True)),
                ('fundusPhotographs', models.ImageField(upload_to='images/')),
                ('OCT', models.CharField(max_length=1000, null=True)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
