# Generated by Django 5.0 on 2024-01-07 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_patientrecord_age_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chatRoomID', models.AutoField(primary_key=True, serialize=False)),
                ('chatRoomName', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='opthID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ophthalmologist'),
        ),
        migrations.AddField(
            model_name='message',
            name='stafferID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinicstaff'),
        ),
    ]
