# Generated by Django 5.0 on 2024-01-08 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_chatroom_message_opthid_message_stafferid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicstaff',
            name='clinicID',
        ),
        migrations.AddField(
            model_name='clinic',
            name='stafferID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinicstaff'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='chatRoomName',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
