# Generated by Django 5.0 on 2024-01-08 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_remove_clinicstaff_clinicid_clinic_stafferid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='clinicID',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='message',
            name='opthID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ophthalmologist'),
        ),
        migrations.AlterField(
            model_name='message',
            name='stafferID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinicstaff'),
        ),
        migrations.AlterField(
            model_name='message',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
    ]
