# Generated by Django 5.0 on 2024-01-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_message_clinicid_alter_message_opthid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
    ]
