# Generated by Django 4.2.3 on 2024-01-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_chatroom_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_Archieve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='reciever',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
