# Generated by Django 4.2.3 on 2024-01-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_message_is_archieve_message_reciever_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('historyRecordID', models.AutoField(primary_key=True, serialize=False)),
                ('is_Hypertention', models.BooleanField(default=False, null=True)),
                ('recordDate1', models.DateField(blank=True, null=True)),
                ('is_HeartProblem', models.BooleanField(default=False, null=True)),
                ('recordDate2', models.DateField(blank=True, null=True)),
                ('is_Diabetes', models.BooleanField(default=False, null=True)),
                ('recordDate3', models.DateField(blank=True, null=True)),
                ('is_Stroke', models.BooleanField(default=False, null=True)),
                ('recordDate4', models.DateField(blank=True, null=True)),
                ('is_Asthma', models.BooleanField(default=False, null=True)),
                ('recordDate5', models.DateField(blank=True, null=True)),
                ('is_DiagnosedNone', models.BooleanField(default=False, null=True)),
                ('recordDate6', models.DateField(blank=True, null=True)),
                ('otherDiagnosedHealth', models.CharField(max_length=1000, null=True)),
                ('recordDate7', models.DateField(blank=True, null=True)),
                ('is_Smoking', models.BooleanField(default=False, null=True)),
                ('is_SmokingFreq', models.CharField(max_length=1000, null=True)),
                ('is_SmokingYear', models.CharField(max_length=1000, null=True)),
                ('is_Alcohol', models.BooleanField(default=False, null=True)),
                ('is_AlcoholFreq', models.CharField(max_length=1000, null=True)),
                ('recordDate8', models.DateField(blank=True, null=True)),
                ('is_HabitsNone', models.BooleanField(default=False, null=True)),
                ('medicinesAller', models.CharField(max_length=1000, null=True)),
                ('foodsAller', models.CharField(max_length=1000, null=True)),
                ('otherAller', models.CharField(max_length=1000, null=True)),
                ('is_AllergiesNone', models.BooleanField(default=False, null=True)),
                ('is_Cataract', models.BooleanField(default=False, null=True)),
                ('is_Glaucama', models.BooleanField(default=False, null=True)),
                ('is_RetinalDisease', models.BooleanField(default=False, null=True)),
                ('othersEyeHis', models.CharField(max_length=1000, null=True)),
                ('is_EHNone', models.BooleanField(default=False, null=True)),
                ('eyeSurgeries', models.CharField(max_length=1000, null=True)),
                ('is_GlaucamaF', models.BooleanField(default=False, null=True)),
                ('is_HypertentionF', models.BooleanField(default=False, null=True)),
                ('is_Blindness', models.BooleanField(default=False, null=True)),
                ('is_DiabetesF', models.BooleanField(default=False, null=True)),
                ('is_CataractF', models.BooleanField(default=False, null=True)),
                ('is_FHNone', models.BooleanField(default=False, null=True)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
            ],
        ),
    ]
