# Generated by Django 4.2.3 on 2024-01-20 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_patientmedicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='dryEyeTest',
            fields=[
                ('dryEyeID', models.AutoField(primary_key=True, serialize=False)),
                ('od_DryEye', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_DryEye', models.CharField(blank=True, max_length=1000, null=True)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
            ],
        ),
        migrations.CreateModel(
            name='ocularHealthExamination',
            fields=[
                ('oheID', models.AutoField(primary_key=True, serialize=False)),
                ('od_Lids_Lashes', models.CharField(blank=True, max_length=1000, null=True)),
                ('od_Bulbar', models.CharField(blank=True, max_length=1000, null=True)),
                ('od_Palpebral', models.CharField(blank=True, max_length=1000, null=True)),
                ('od_Cornea', models.CharField(blank=True, max_length=1000, null=True)),
                ('od_ChamgerAngle', models.CharField(blank=True, max_length=1000, null=True)),
                ('od_Iris', models.CharField(blank=True, max_length=1000, null=True)),
                ('od_Lens', models.CharField(blank=True, max_length=1000, null=True)),
                ('od_Tonometry', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_Lids_Lashes', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_Bulbar', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_Palpebral', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_Cornea', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_ChamgerAngle', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_Iris', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_Lens', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_Tonometry', models.CharField(blank=True, max_length=1000, null=True)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
            ],
        ),
        migrations.CreateModel(
            name='Refraction',
            fields=[
                ('refractionID', models.AutoField(primary_key=True, serialize=False)),
                ('subRef_OD', models.CharField(blank=True, max_length=1000, null=True)),
                ('subRef_OS', models.CharField(blank=True, max_length=1000, null=True)),
                ('va_OD', models.CharField(blank=True, max_length=1000, null=True)),
                ('va_OS', models.CharField(blank=True, max_length=1000, null=True)),
                ('pd_OD', models.CharField(blank=True, max_length=1000, null=True)),
                ('pd_OS', models.CharField(blank=True, max_length=1000, null=True)),
                ('autRef_OD', models.CharField(blank=True, max_length=1000, null=True)),
                ('autRef_OS', models.CharField(blank=True, max_length=1000, null=True)),
                ('od_Refraction', models.CharField(blank=True, max_length=1000, null=True)),
                ('os_Refraction', models.CharField(blank=True, max_length=1000, null=True)),
                ('remarks_Refraction', models.CharField(blank=True, max_length=2000, null=True)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
            ],
        ),
        migrations.DeleteModel(
            name='PatientRecord',
        ),
    ]
