# Generated by Django 4.2.3 on 2024-01-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_dryeyetest_ocularhealthexamination_refraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='walkInPatient',
            fields=[
                ('walkInPatientID', models.AutoField(primary_key=True, serialize=False)),
                ('dateRecorded', models.DateField(null=True)),
                ('homeAddress', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='dryeyetest',
            name='dateRecorded',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ocularhealthexamination',
            name='dateRecorded',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='dateRecorded',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='refraction',
            name='dateRecorded',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False)),
                ('dateRecorded', models.DateField(null=True)),
                ('sessionNotes', models.CharField(max_length=3000, null=True)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('patientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
                ('walkInPatientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient')),
            ],
        ),
    ]
