# Generated by Django 4.2.3 on 2024-01-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_walkinpatient_dryeyetest_daterecorded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocularhealthexamination',
            name='dateRecorded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
