# Generated by Django 4.2.3 on 2024-01-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_ocularhealthexamination_daterecorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocularhealthexamination',
            name='dateRecorded',
            field=models.DateField(null=True),
        ),
    ]
