# Generated by Django 4.2.3 on 2024-01-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_ocularhealthexamination_daterecorded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate6',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate7',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate8',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
