# Generated by Django 5.0 on 2024-01-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_patientmedicalhistory_recorddate1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicalhistory',
            name='recordDate6',
        ),
        migrations.CreateModel(
            name='PatientPersonalInformation',
            fields=[
                ('perInID', models.AutoField(primary_key=True, serialize=False)),
                ('dateRecorded', models.DateField(null=True)),
                ('civilStatus', models.CharField(max_length=1000, null=True)),
                ('Occupation', models.CharField(max_length=1000, null=True)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
            ],
        ),
    ]
