# Generated by Django 5.0 on 2024-01-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_remove_patientmedicalhistory_recorddate6_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walkinpatient',
            old_name='dateRecorded',
            new_name='bday',
        ),
        migrations.RenameField(
            model_name='walkinpatient',
            old_name='walkInPatientID',
            new_name='userID',
        ),
        migrations.AddField(
            model_name='walkinpatient',
            name='contactNum',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='walkinpatient',
            name='firstName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='walkinpatient',
            name='lastName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='walkinpatient',
            name='middleName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='walkinpatient',
            name='sex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='walkinpatient',
            name='homeAddress',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
