# Generated by Django 5.0 on 2024-01-23 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_rename_daterecorded_walkinpatient_bday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinpatient',
            name='clinicID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic'),
        ),
    ]
