# Generated by Django 5.0 on 2024-01-24 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_walkinpatient_clinicid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walkinpatient',
            old_name='userID',
            new_name='walkInID',
        ),
        migrations.RemoveField(
            model_name='walkinpatient',
            name='clinicID',
        ),
        migrations.AddField(
            model_name='clinic',
            name='walkInID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
    ]
