# Generated by Django 5.0 on 2024-01-24 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_rename_userid_walkinpatient_walkinid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='walkInID',
        ),
        migrations.AddField(
            model_name='booking',
            name='walkInID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
        migrations.AddField(
            model_name='dryeyetest',
            name='walkInID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
        migrations.AddField(
            model_name='message',
            name='walkInID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
        migrations.AddField(
            model_name='ocularhealthexamination',
            name='walkInID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
        migrations.AddField(
            model_name='patientclinicalobservation',
            name='walkInID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='walkInID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
        migrations.AddField(
            model_name='patientpersonalinformation',
            name='walkInID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
        migrations.AddField(
            model_name='refraction',
            name='walkInID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
        migrations.AddField(
            model_name='walkinpatient',
            name='clinicID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='clinicID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
    ]
