# Generated by Django 5.0 on 2024-01-24 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_remove_clinic_walkinid_booking_walkinid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='patientID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
    ]
