# Generated by Django 5.0 on 2024-01-24 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_alter_patientmedicalhistory_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='walkInID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
    ]
