# Generated by Django 5.0 on 2024-01-24 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_patientmedicalhistory_patientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryeyetest',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
        migrations.AlterField(
            model_name='dryeyetest',
            name='walkInID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
        migrations.AlterField(
            model_name='ocularhealthexamination',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
        migrations.AlterField(
            model_name='ocularhealthexamination',
            name='walkInID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
        migrations.AlterField(
            model_name='patientpersonalinformation',
            name='clinicID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic'),
        ),
        migrations.AlterField(
            model_name='patientpersonalinformation',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
        migrations.AlterField(
            model_name='refraction',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
        migrations.AlterField(
            model_name='refraction',
            name='walkInID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
    ]
