# Generated by Django 5.0 on 2024-01-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_dryeyetest_patientid_alter_dryeyetest_walkinid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkinpatient',
            name='clinicID',
        ),
    ]
