# Generated by Django 5.0 on 2024-01-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_remove_walkinpatient_clinicid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercontacts',
            name='walkInID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
    ]
