# Generated by Django 5.0 on 2024-01-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_usercontacts_walkinid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_WalkIn',
            field=models.BooleanField(default=False),
        ),
    ]
