# Generated by Django 5.0 on 2024-01-24 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_booking_is_walkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='serviceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.services'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='walkInID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
    ]
