# Generated by Django 5.0 on 2024-01-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_alter_booking_serviceid_alter_booking_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_WalkIn',
        ),
    ]
