# Generated by Django 5.0 on 2024-01-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_remove_booking_is_walkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_Success',
            field=models.BooleanField(default=False),
        ),
    ]
