# Generated by Django 5.0 on 2024-01-25 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_booking_is_success'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('sessionID', models.AutoField(primary_key=True, serialize=False)),
                ('dateRecorded', models.DateField(null=True)),
                ('sessionNotes', models.CharField(max_length=3000, null=True)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('patientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
                ('walkInPatientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient')),
            ],
        ),
    ]
