# Generated by Django 5.0 on 2024-01-25 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient'),
        ),
        migrations.AlterField(
            model_name='session',
            name='walkInPatientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient'),
        ),
    ]
