# Generated by Django 5.0 on 2024-01-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_alter_session_patientid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='aggrement',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
