# Generated by Django 5.0 on 2024-01-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_patientmedicalhistory_aggrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReview',
            fields=[
                ('patientRevID', models.AutoField(primary_key=True, serialize=False)),
                ('dateRecorded', models.DateField(null=True)),
                ('rate', models.CharField(blank=True, max_length=1000, null=True)),
                ('review', models.CharField(blank=True, max_length=1000, null=True)),
                ('clinicID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clinic')),
                ('patientID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.userpatient')),
                ('walkInID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.walkinpatient')),
            ],
        ),
    ]
