# Generated by Django 5.0 on 2024-01-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_patientreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_EmailVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicstaff',
            name='auth_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clinicstaff',
            name='is_EmailVerified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ophthalmologist',
            name='auth_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ophthalmologist',
            name='is_EmailVerified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='userpatient',
            name='auth_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpatient',
            name='is_EmailVerified',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='walkinpatient',
            name='auth_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='walkinpatient',
            name='is_EmailVerified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
