# Generated by Django 5.0 on 2024-01-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_clinic_is_emailverified_clinicstaff_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicstaff',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ophthalmologist',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpatient',
            name='age',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
