# Generated by Django 5.0 on 2024-01-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_clinicstaff_age_ophthalmologist_age_userpatient_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='calendar',
            new_name='DashCalendar',
        ),
    ]
