# Generated by Django 4.2.3 on 2024-02-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
