# Generated by Django 4.2.3 on 2024-02-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_alter_patientmedicalhistory_recorddate1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='eyeSurgeries',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='foodsAller',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='is_AlcoholFreq',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='is_SmokingFreq',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='is_SmokingYear',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='medicinesAller',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='otherAller',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='othersEyeHis',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalhistory',
            name='recordDate8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
