# Generated by Django 5.0 on 2024-02-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_alter_patientpersonalinformation_walkinid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='is_Astigmatism',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='is_ColorBlindness',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='is_DiabeticRetinopathy',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='is_DryEyeSyndrome',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='is_Keratoconus',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='is_MacularDegeneration',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='is_Strabismus',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='is_Uveitis',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
