# Generated by Django 5.0 on 2024-02-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_requestrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='walkInID',
        ),
    ]
